In [1]:
import numpy as np; ####vnik
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
###library imported
###Pandas acts as a wrapper over these libraries, allowing you to access many of matplotlib's and NumPy's methods with less code.

In [4]:
dataset = pd.read_csv("Data.csv")
A = dataset.iloc[:, :-1].values #####[:, :-1] the colans before comma is for including all the rows of the data set and :-1 after comma represents all the column except the last one 
B = dataset.iloc[:, -1].values ######-1 gives the last column in our dataset because we dont have to use collans

In [5]:
print(A)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(B)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [7]:
# now importing dataset has been taken care of now moving to the next part

In [8]:
# now we are going to take care of missing data in our dataset

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')  #it replaces all the nan values in our dataset to the mean of their column
imputer.fit(A[:,1:3])
A[:,1:3]=imputer.transform(A[:,1:3]) #it will replace the missing values

In [11]:
print(A)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
### now here we're going to encode categorical data

In [13]:
### encoding the independent variable 

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])] , remainder='passthrough') #onehotencoder turn the value of country in zero one code to make it understandable for system
A=np.array(ct.fit_transform(A)) #np is because we want our output in numpy array

In [15]:
print(A)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
###encoding the dependent variable

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
B=le.fit_transform(B) #we dont need numpy here becuse its a dependent variable


In [19]:
print(B)

[0 1 0 0 1 1 0 1 0 1]


In [20]:
#now splitting the data set into training and testing set

In [21]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y=train_test_split(A, B, test_size=.15,random_state=1)


In [22]:
print(train_X)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [23]:
print(test_X)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [24]:
print(train_Y)

[0 1 0 0 1 1 0 1]


In [25]:
print(test_Y)

[0 1]


In [27]:
###Feature Scaling###

In [30]:
# #I will be discussing the top 5 of the most commonly used feature scaling techniques.
# Absolute Maximum Scaling.
# Min-Max Scaling.
# Normalization.
# Standardization.
# Robust Scaling.

In [33]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
train_X[:,3:5]=SS.fit_transform(train_X[:,3:])
test_X[:,3:5]=SS.transform(test_X[:,3:])#we use only transform because we want to test out data set with the same features as used in our train data set 

In [34]:
print(train_X)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [36]:
print(test_X)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


In [37]:
# Steps in Data Preprocessing in Machine Learning
# Acquire the dataset. Acquiring the dataset is the first step in data preprocessing in machine learning. ...
# Import all the crucial libraries. ...
# Import the dataset. ...
# Identifying and handling the missing values. ...
# Encoding the categorical data. ...
# Splitting the dataset. ...
# Feature scaling.