#### Y=Const+a1x1+a2x2+a3x3+....+anxn
#### where Y is dependent variable and x1 x2 x3 ..... xn are independent varable


### Assumption of a linear regression
#### 1 linearity
#### 2 Homoscedasticity
#### 3 Multivariate normality
#### 4 Independence of errors
#### 5 Lack of multicollinearity

### understanding p- value
#### The P Value is the probability of seeing the effect(E) when the null hypothesis(proposes that there is no difference between certain characteristics of a population (or data-generating process)) is true for ex if we toss coin two times and we get tails both times then the probability of coming tales second time is .25 if we toss it 4 times then the probabilty of tales coming consecutivey 4th time is .0625 this is p-value probabilty at a point (.25  , .0625,.....etc)


##  process to build our model step by step
### we have to check which variable to keep and which variable to throw out to make our model more reliable
### 5 methods to build our models  1=> All-in 2=> backward elimination 3=> forward selection 4=> Bidirectional Elimination 5=> Score elimination
### All-in   ->when we use all our variables in the model
### Backward Elimination -> Select the significance level to stay in the model  ...E.g SL=0.05.------------------>Fit the full model with all predictors------------>Consider the predictor with the highest p-values ifp>SL then go to step 4 other wise finish the model-----------------------> Remove the predictor-------------------> fit the model without this variable and repeat the step 3 again 
### Forward Selection->Select the significance level to enter the model (e.g SL=0.05)--------------> fit all the regression models y~xn select the one with the lowest P-Value----------------> keep the variable and fit all the possible models with one extra predictor added to the one(s) you already have -----------------------> consider the predictor with the lowest P-value. if p< SL got to step 3 otherwise go to FIN
### Bidirectional Elimination->Select a significant level to enter and  to stay in the model SL_ENTER=0.05,SL_STAY=0.05-----------------> perform the next step of forward selection( new variable must have P< SL_ENTER to enter)-------------->perform all of the steps of the backward elimination process.(old variables must have p< SL_STAY to stay) then perfor the step 2 again ...we keep doing that until some point we dont have any new variable to enter nd old variable to exit 
### ALL POSSIBLE MODEL->select a criterion of goodness of fit (e.g akaike criterion)-----------------> all possible regression model 2^N -1 combination-----------------> select the one with the best Criterion--------> finish model  -----> not good when you have to many columns and very resource consuming

In [1]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
### importing dataset 
dataset=pd.read_csv('50_Startups.csv')
X=dataset.iloc[:, :-1].values
Y=dataset.iloc[:, -1].values

In [3]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [4]:
print(Y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [5]:
###now encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [6]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [7]:
### splitting the data into training set anmd test set 
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y= train_test_split(X,Y,train_size=.80,random_state=0)

In [8]:
### training the multiple linear regression model on the training set 
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(train_X,train_Y)

LinearRegression()

In [9]:
### ther are total of 4 features in our model so we cant just plot a graph because we need a five dimensional graph to represent this

In [13]:
y_pred = regressor.predict(test_X)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), test_Y.reshape(len(test_Y),1)),1))## 1 represent number of column len() represent number of rows====but the 1 use after reshape brackets used for vertical concatenation and 0 used for horixontal concatenation

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
